### PR TITLE
Custom Endpoint in target deployment org

### PR DESCRIPTION
**Pull request by Torsen**
Hi guys,

How are you? You are awesome creating this examples 👍 

I have added a new Enviroment variable to save the endpoint of the target deployment org, because there is hardcoded the sandbox's endpoint and know you can use developer org, and custom domains.

Thanks for your time.

### CODE REVIEW

**Comment by Torsen** [comment]
update my work email in my github account

**Comment by clairebianchi** [comment]
@douglascayers can you please take a look at this PR?

**Comment by douglascayers** [comment]
Hi @Torsen, thanks for the update to more easily support login urls without having to modify the config yml file. I'll review and follow up soon.

cc @clairebianchi

**Comment by Torsen** [comment]
Hi @douglascayers @clairebianchi, I am at your service guys

**Pull request merged**
